-- Generated by tools/notplater-profile.py. Do not edit: change the look in NotPlater on
-- your own machine, /reload so the client writes it, and re-run the tool.
--
-- Applied by SanctuaryVoice at login when the version is newer than the one this
-- character last received: written into NotPlater's profiles as 'Sanctuary' and switched to,
-- and registered as NotPlater's defaults for the session.

SanctuaryVoiceNotPlaterProfile = {
    version = 7,
    name = "Sanctuary",
    -- NotPlater's minimap button, in degrees round the minimap (LibDBIcon's minimapPos).
    minimapPos = 147.2032,
    data = {
        ["buffs"] = {
            ["auraFrame1"] = {
                ["height"] = 12,
                ["width"] = 22,
                ["yOffset"] = 8,
            },
            ["auraTimer"] = {
                ["general"] = {
                    ["name"] = "Friz Quadrata TT",
                    ["showDecimals"] = true,
                    ["size"] = 9,
                },
                ["position"] = {
                    ["xOffset"] = -4,
                    ["yOffset"] = 2,
                },
            },
            ["general"] = {
                ["alpha"] = 0.84999996423721,
                ["iconSpacing"] = 2,
                ["stackSimilarAuras"] = true,
            },
            ["stackCounter"] = {
                ["general"] = {
                    ["name"] = "Friz Quadrata TT",
                    ["size"] = 9,
                },
                ["position"] = {
                    ["xOffset"] = 7,
                    ["yOffset"] = -4,
                },
            },
            ["tracking"] = {
                ["lists"] = {
                },
            },
        },
        ["castBar"] = {
            ["spellIcon"] = {
                ["border"] = {
                    ["enable"] = true,
                    ["iconZoom"] = 100,
                },
                ["position"] = {
                    ["xOffset"] = -2,
                    ["yOffset"] = 7,
                },
                ["size"] = {
                    ["height"] = 22,
                    ["width"] = 22,
                },
            },
            ["spellNameText"] = {
                ["general"] = {
                    ["border"] = "",
                    ["color"] = {
                        [1] = 0.95294117647059,
                        [3] = 0.9921568627451,
                    },
                    ["name"] = "Friz Quadrata TT",
                    ["size"] = 9,
                },
                ["position"] = {
                    ["anchor"] = "TOPLEFT",
                    ["xOffset"] = 3.4099960327148,
                    ["yOffset"] = 0.19999694824219,
                },
                ["shadow"] = {
                    ["enable"] = true,
                    ["xOffset"] = 1,
                    ["yOffset"] = -1,
                },
            },
            ["spellTimeText"] = {
                ["general"] = {
                    ["border"] = "",
                    ["name"] = "Friz Quadrata TT",
                    ["size"] = 9,
                },
                ["position"] = {
                    ["xOffset"] = -1,
                },
                ["shadow"] = {
                    ["enable"] = true,
                    ["xOffset"] = 1,
                    ["yOffset"] = -1,
                },
            },
            ["statusBar"] = {
                ["background"] = {
                    ["color"] = {
                        [1] = 0,
                        [2] = 0,
                        [3] = 0,
                        [4] = 0.79781,
                    },
                },
                ["border"] = {
                    ["enable"] = true,
                },
                ["general"] = {
                    ["color"] = {
                        [1] = 1,
                        [2] = 0.85882352941176,
                        [4] = 0.96000000089407,
                    },
                },
                ["position"] = {
                    ["yOffset"] = 0,
                },
                ["size"] = {
                    ["height"] = 8,
                    ["width"] = 120,
                },
            },
        },
        ["healthBar"] = {
            ["healthText"] = {
                ["general"] = {
                    ["border"] = "",
                    ["displayType"] = "percent",
                    ["name"] = "Friz Quadrata TT",
                    ["size"] = 8,
                },
                ["position"] = {
                    ["anchor"] = "TOPLEFT",
                    ["xOffset"] = 1,
                    ["yOffset"] = -5,
                },
                ["shadow"] = {
                    ["enable"] = true,
                    ["xOffset"] = 1,
                    ["yOffset"] = -1,
                },
            },
            ["statusBar"] = {
                ["background"] = {
                    ["color"] = {
                        [1] = 0.043137254901961,
                        [2] = 0.043137254901961,
                        [3] = 0.043137254901961,
                        [4] = 0.5,
                    },
                },
                ["general"] = {
                    ["useClassColors"] = true,
                },
                ["size"] = {
                    ["width"] = 120,
                },
            },
        },
        ["icons"] = {
            ["bossIcon"] = {
                ["position"] = {
                    ["anchor"] = "RIGHT",
                    ["xOffset"] = 5,
                },
            },
            ["classIcon"] = {
                ["position"] = {
                    ["anchor"] = "BOTTOM",
                    ["xOffset"] = -10,
                    ["yOffset"] = 20,
                },
                ["size"] = {
                    ["height"] = 12,
                    ["width"] = 12,
                },
            },
            ["eliteIcon"] = {
                ["position"] = {
                    ["anchor"] = "BOTTOMRIGHT",
                    ["yOffset"] = 22,
                },
            },
            ["factionIcon"] = {
                ["general"] = {
                    ["enable"] = false,
                },
                ["position"] = {
                    ["anchor"] = "BOTTOMRIGHT",
                    ["xOffset"] = -5,
                    ["yOffset"] = 6,
                },
            },
            ["npcIcons"] = {
                ["general"] = {
                    ["enable"] = false,
                },
            },
            ["raidIcon"] = {
                ["position"] = {
                    ["anchor"] = "LEFT",
                    ["xOffset"] = -2,
                },
                ["size"] = {
                    ["height"] = 13.9999997615814,
                    ["width"] = 13.9999997615814,
                },
            },
        },
        ["levelText"] = {
            ["general"] = {
                ["enable"] = false,
                ["name"] = "Friz Quadrata TT",
                ["opacity"] = 1,
            },
            ["position"] = {
                ["anchor"] = "RIGHT",
                ["xOffset"] = 0,
                ["yOffset"] = -2.4599990844727,
            },
            ["shadow"] = {
                ["xOffset"] = 1,
                ["yOffset"] = -1,
            },
        },
        ["nameText"] = {
            ["general"] = {
                ["maxLetters"] = 16,
                ["name"] = "Friz Quadrata TT",
                ["size"] = 12,
            },
            ["position"] = {
                ["anchor"] = "TOPLEFT",
                ["xOffset"] = 2,
                ["yOffset"] = 8,
            },
            ["shadow"] = {
                ["xOffset"] = 1,
                ["yOffset"] = -1,
            },
        },
        ["speakingIndicator"] = {
            ["general"] = {
                ["color"] = {
                    [1] = 1,
                    [2] = 0.82,
                    [3] = 0.35,
                    [4] = 1,
                },
                ["enable"] = true,
            },
            ["position"] = {
                ["anchor"] = "TOP",
                ["anchorTarget"] = "healthBar",
                ["auraGap"] = 8,
                ["riseAboveAuras"] = true,
                ["xOffset"] = 0,
                ["yOffset"] = 24,
            },
            ["size"] = {
                ["height"] = 15,
                ["spacing"] = 2,
                ["width"] = 4,
            },
        },
        ["stacking"] = {
            ["componentOrdering"] = {
                ["components"] = {
                    [10] = "castSpellTimeText",
                    [11] = "levelText",
                    [12] = "targetOverlay",
                    [13] = "targetIndicator",
                    [14] = "targetBorder",
                    [15] = "mouseoverHighlight",
                    [16] = "bossIcon",
                    [3] = "targetHighlight",
                    [4] = "nameText",
                    [5] = "npcIcons",
                    [6] = "castBar",
                    [7] = "raidIcon",
                    [8] = "castSpellIcon",
                    [9] = "castSpellNameText",
                },
            },
        },
        ["target"] = {
            ["border"] = {
                ["highlight"] = {
                    ["color"] = {
                        [1] = 1,
                        [2] = 1,
                        [4] = 1,
                    },
                    ["enable"] = false,
                    ["thickness"] = 18,
                },
                ["indicator"] = {
                    ["selection"] = "NONE",
                },
            },
            ["mouseoverHighlight"] = {
                ["opacity"] = 0.1499999910593,
            },
            ["nonTargetShading"] = {
                ["opacity"] = 0.59999996423721,
            },
            ["overlay"] = {
                ["color"] = {
                    [4] = 0,
                },
            },
        },
    },
}
