/*
 * mod-sanctuary-gm - the Timekeeper, the game masters' class
 *
 * A game master's own character wears a class nobody else can have, so it reads as staff on
 * sight: "Level 80 Human Timekeeper". It lives in class slot 10, the one hole in 3.3.5a's
 * list between Warlock and Druid, so Death Knight is untouched and stays free to open up.
 *
 * Nobody can choose it. The creation screen is patched not to offer it and this module
 * refuses it anyway, because the screen is only the client's opinion. The only way in is
 *
 *     .gmclass set <name>               make a logged-in character a Timekeeper
 *     .gmclass revert <name> <class>    and back again, e.g. `.gmclass revert Aldric paladin`
 *
 * and the character has to belong to an account with game master security - the same
 * SanctuaryGM.RequiredSecurity the panel answers to.
 *
 *
 * ITS TWO SPELLS, and the only ones it has: 81014 "True Visage", a dragon at half scale for
 * a fight indoors, and 81015 "Winged Visage", a drake with an epic mount's ground and flight
 * speed for getting somewhere. Both are infinite self-auras, so the buff is the toggle, and
 * taking one puts the other away. The speed rides on the spell rather than being set here,
 * because a hand-set speed is recalculated away by the next aura or mount.
 *
 *
 * WHAT BECOMING A TIMEKEEPER DOES. The old class goes: its talents (every spec), its glyphs,
 * and every skill the new class may not hold - which takes every spell that skill taught
 * with it. What every class shares stays: professions, riding, languages, mounts and pets.
 * The Timekeeper then learns every language (fluent), every profession (Grand Master, 450)
 * and every weapon and armour proficiency (weapon skills at the cap for its level), so a
 * game master can understand anyone and dress for whatever an event needs. It has no class
 * spells of its own; game masters have commands. The same kit is topped up at every
 * Timekeeper's login, and `.gmclass set` on a Timekeeper re-teaches it on the spot.
 *
 * The character is then logged out. A class is not something the client expects to change
 * under it, and a fresh login is the one path that rebuilds everything - stats, power type,
 * spellbook, action bars - from the new class rather than patching the old one in place.
 *
 *
 * WHAT HAS TO EXIST FIRST, and all of it is generated by tools/assets/make-patch.py from one
 * number (GM_CLASS_ID) so the halves cannot drift:
 *
 *   the client   ChrClasses row 10, or the class has no name on anyone's screen
 *   the server   chrclasses_dbc, skillraceclassinfo_dbc, playercreateinfo and
 *                player_class_stats rows (data/sql/db-world/..._sanctuary_gm_class.sql).
 *                Without creation info a Timekeeper cannot even be loaded, and without
 *                stats for every level the worldserver will not start.
 */

#include "AccountScript.h"
#include "AllSpellScript.h"
#include "CharacterCache.h"
#include "Chat.h"
#include "Spell.h"
#include "SpellAuraEffects.h"
#include "UnitScript.h"
#include "CommandScript.h"
#include "Config.h"
#include "DBCStores.h"
#include "Log.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "PlayerScript.h"
#include "RBAC.h"
#include "ScriptMgr.h"
#include "SpellMgr.h"
#include "WorldSession.h"

#include <algorithm>
#include <cctype>
#include <string>
#include <vector>

using namespace Acore::ChatCommands;

namespace
{
    // Must match GM_CLASS_ID in tools/assets/make-patch.py.
    constexpr uint8 CLASS_TIMEKEEPER = 10;

    /*
     * The spell behind every weapon and armour skill, and the skill. Learning the spell
     * grants the skill, and the SQL gives the Timekeeper a SkillRaceClassInfo row for each -
     * without that row the skill, and the spell with it, would be stripped again at the
     * next login.
     */
    struct Proficiency
    {
        uint32 spell;
        uint16 skill;
    };

    constexpr Proficiency WeaponsAndArmour[] =
    {
        { 9078,  415 },     // Cloth
        { 9077,  414 },     // Leather
        { 8737,  413 },     // Mail
        { 750,   293 },     // Plate Mail
        { 9116,  433 },     // Shield
        { 201,   43  },     // One-Handed Swords
        { 196,   44  },     // One-Handed Axes
        { 198,   54  },     // One-Handed Maces
        { 202,   55  },     // Two-Handed Swords
        { 197,   172 },     // Two-Handed Axes
        { 199,   160 },     // Two-Handed Maces
        { 200,   229 },     // Polearms
        { 227,   136 },     // Staves
        { 1180,  173 },     // Daggers
        { 15590, 473 },     // Fist Weapons
        { 203,   162 },     // Unarmed
        { 264,   45  },     // Bows
        { 266,   46  },     // Guns
        { 5011,  226 },     // Crossbows
        { 2567,  176 },     // Thrown
        { 5009,  228 },     // Wands
        { 674,   118 },     // Dual Wield
        { 204,   95  },     // Defense
    };

    /*
     * The class's two forms.
     *
     * Spells rather than panel buttons, because a form is something you flick on and off
     * from an action bar mid-event. Each is an infinite self-aura, so the buff itself is the
     * toggle: right-click it, or cast it again, and the form comes off.
     *
     * What the aura cannot do is the morph. A DBC transform aura takes a creature ENTRY and
     * these are DISPLAYS, so the module does the morph and the scale when the aura goes on
     * and comes off. The speed, on the other hand, is on the spell row and not here - see
     * the SQL for why a hand-set speed does not last.
     */
    /*
     * The puff of smoke a druid changes shape inside. Without it a form is one model
     * silently replacing another, which reads as a glitch rather than a change.
     *
     * **This is a SpellVisualKit id, not a SpellVisual id, and the two are different
     * tables.** SMSG_PLAY_SPELL_VISUAL carries a kit index; a spell row's SpellVisualID
     * points at a SpellVisual, which in turn names up to six kits for the stages of a cast.
     * Cat Form casts with SpellVisual 4228, whose impact kit - the puff that lands on the
     * caster - is 3610, and that is what this is. Sending 4228 here draws nothing at all,
     * silently, which is exactly what it did the first time.
     *
     * Played by the server rather than set on the spell row, because a spell's own visual
     * plays when it is CAST and nothing plays when a buff is cancelled - and the change back
     * wants covering just as much as the change out.
     *
     * The kit is Sanctuary's own, added by tools/assets/make-patch.py: it is Cat Form's
     * impact kit with the puff enlarged, because at its own size - built for a person - the
     * smoke was lost against a dragon. The size is client data and cannot be sent from
     * here, since the packet carries a kit id and nothing else. Change SMOKE_SCALE there.
     */
    constexpr uint32 SHAPESHIFT_SMOKE = 15600;

    struct Form
    {
        uint32 spell;
        uint32 display;
        float scale;
        bool flies;
        uint32 visual;
    };

    constexpr Form Forms[] =
    {
        // A bronze dragon at its own size - display 19373, which the Steward of Time wears,
        // and whose model already carries a half scale of its own.
        { 81014, 19373, 1.0f, false, SHAPESHIFT_SMOKE },

        // A drake, at its own size, for getting somewhere.
        { 81015, 25852, 1.0f, true,  SHAPESHIFT_SMOKE },
    };

    constexpr Form const* FindForm(uint32 spell)
    {
        for (Form const& form : Forms)
            if (form.spell == spell)
                return &form;

        return nullptr;
    }

    /*
     * Every profession, primary and secondary, by its Grand Master rank. Teaching that rank
     * alone grants the skill with a 450 cap and puts the profession in the spellbook; the
     * lower ranks are only stepping stones at a trainer. Recipes are not included - there
     * are thousands, and `.learn all recipes <profession>` is there for those.
     */
    constexpr Proficiency Professions[] =
    {
        { 51304, 171 },     // Alchemy
        { 51300, 164 },     // Blacksmithing
        { 51313, 333 },     // Enchanting
        { 51306, 202 },     // Engineering
        { 50300, 182 },     // Herbalism
        { 45363, 773 },     // Inscription
        { 51311, 755 },     // Jewelcrafting
        { 51302, 165 },     // Leatherworking
        { 50310, 186 },     // Mining
        { 50305, 393 },     // Skinning
        { 51309, 197 },     // Tailoring
        { 51296, 185 },     // Cooking
        { 45542, 129 },     // First Aid
        { 51294, 356 },     // Fishing
    };

    uint32 RequiredSecurity()
    {
        return sConfigMgr->GetOption<uint32>("SanctuaryGM.RequiredSecurity", uint32(SEC_GAMEMASTER));
    }

    std::string Folded(std::string_view text)
    {
        std::string out;

        for (char c : text)
            if (!std::isspace(static_cast<unsigned char>(c)))
                out += char(std::tolower(static_cast<unsigned char>(c)));

        return out;
    }

    /// The class's name as the server has it. Every row carries at least one locale.
    std::string ClassName(uint8 classId)
    {
        if (ChrClassesEntry const* entry = sChrClassesStore.LookupEntry(classId))
            for (char const* name : entry->name)
                if (name && *name)
                    return name;

        return "class " + std::to_string(classId);
    }

    /// "paladin", "Death Knight", "deathknight" or a number. 0 if it is none of those.
    uint8 ParseClass(std::string_view text)
    {
        std::string const wanted = Folded(text);

        bool const numeric = !wanted.empty() && wanted.size() <= 2 && std::all_of(wanted.begin(), wanted.end(),
            [](char c) { return std::isdigit(static_cast<unsigned char>(c)) != 0; });

        if (numeric)
        {
            uint32 const id = std::stoul(wanted);
            return id < MAX_CLASSES && sChrClassesStore.LookupEntry(id) ? uint8(id) : 0;
        }

        for (ChrClassesEntry const* entry : sChrClassesStore)
            for (char const* name : entry->name)
                if (name && *name && Folded(name) == wanted)
                    return uint8(entry->ClassID);

        return 0;
    }

    /*
     * Talents and glyphs, in every spec rather than just the active one.
     *
     * resetTalents only clears the spec in use, and a talent left in the other one would be
     * learned straight back the first time the character switched to it. Switching through
     * each spec is the core's own way in, and costs nothing here: the character is logged
     * out a moment later anyway.
     */
    void ClearTalentsAndGlyphs(Player* player)
    {
        uint8 const active = player->GetActiveSpec();

        for (uint8 spec = 0; spec < player->GetSpecsCount(); ++spec)
        {
            if (spec != player->GetActiveSpec())
                player->ActivateSpec(spec);

            player->resetTalents(true);

            for (uint8 slot = 0; slot < MAX_GLYPH_SLOT_INDEX; ++slot)
            {
                uint32 const glyph = player->GetGlyph(slot);

                if (!glyph)
                    continue;

                if (GlyphPropertiesEntry const* entry = sGlyphPropertiesStore.LookupEntry(glyph))
                    player->RemoveAurasDueToSpell(entry->SpellId);

                player->SetGlyph(slot, 0, true);
            }
        }

        if (player->GetActiveSpec() != active)
            player->ActivateSpec(active);
    }

    /// Every skill the character's class - as it now is - may not hold. SetSkill(…, 0)
    /// takes each skill's spells with it.
    void DropSkillsTheClassCannotHold(Player* player)
    {
        std::vector<uint16> refused;

        for (uint8 i = 0; i < PLAYER_MAX_SKILLS; ++i)
        {
            uint16 const skill = uint16(player->GetUInt32Value(PLAYER_SKILL_INDEX(i)) & 0xFFFF);

            if (skill && !GetSkillRaceClassInfo(skill, player->getRace(true), player->getClass()))
                refused.push_back(skill);
        }

        for (uint16 skill : refused)
            player->SetSkill(skill, 0, 0, 0);
    }

    /*
     * Every spell whose skills the class - as it now is - may not hold. The same test the
     * core runs at login (Player::CheckSkillLearnedBySpell), run now: removing a skill takes
     * the spells SkillLineAbility lists for it, but talent-learned ranks and the like slip
     * through, and would otherwise be deleted at the next login with an error apiece.
     */
    void DropSpellsTheClassCannotHold(Player* player)
    {
        std::vector<uint32> refused;

        for (auto const& [spellId, spell] : player->GetSpellMap())
        {
            if (spell->State == PLAYERSPELL_REMOVED)
                continue;

            SkillLineAbilityMapBounds const bounds = sSpellMgr->GetSkillLineAbilityMapBounds(spellId);
            bool listed = false;
            bool allowed = false;

            for (auto it = bounds.first; it != bounds.second && !allowed; ++it)
            {
                if (!sSkillLineStore.LookupEntry(it->second->SkillLine))
                    continue;

                listed = true;
                allowed = GetSkillRaceClassInfo(it->second->SkillLine, player->getRace(true), player->getClass()) != nullptr;
            }

            if (listed && !allowed)
                refused.push_back(spellId);
        }

        for (uint32 spellId : refused)
            player->removeSpell(spellId, SPEC_MASK_ALL, false);
    }

    /// Raises a skill to the cap its rank allows. Armour has a single rank, so no cap to reach.
    void RaiseToCap(Player* player, uint16 skill)
    {
        uint16 const cap = player->GetPureMaxSkillValue(skill);

        if (cap > 1 && player->GetPureSkillValue(skill) < cap)
            player->SetSkill(skill, player->GetSkillStep(skill), cap, cap);
    }

    /*
     * Everything a Timekeeper knows: every language, every profession, every weapon and
     * every armour. Safe to run again and again - it only adds what is missing - which is
     * why it also runs at every Timekeeper's login, so one made before something was added
     * here picks it up without anyone asking.
     */
    void TeachTimekeeper(Player* player)
    {
        /*
         * Languages by their spell as well as their skill. The skill is what the server
         * checks, but the client decides for itself what the player can speak, from the
         * language spells it knows - and without one refuses to send a line at all ("You
         * cannot speak that language"). Fluent, at 300: a Timekeeper hears everything,
         * which is also what the voice relay reads from the skill.
         */
        for (LanguageDesc const& language : lang_description)
        {
            if (!language.skill_id)
                continue;

            if (language.spell_id && !player->HasSpell(language.spell_id))
                player->learnSpell(language.spell_id);

            if (player->GetPureSkillValue(language.skill_id) < 300)
                player->SetSkill(language.skill_id, 0, 300, 300);
        }

        for (Proficiency const& p : Professions)
        {
            if (!player->HasSpell(p.spell))
                player->learnSpell(p.spell);

            RaiseToCap(player, p.skill);
        }

        /*
         * A weapon skill learned new starts at 1, which at level 80 is a character that
         * misses nearly everything, so each is raised to the cap for the level - as
         * .maxskill would, but only these: .maxskill fills every skill it finds.
         */
        for (Proficiency const& p : WeaponsAndArmour)
        {
            if (!player->HasSpell(p.spell))
                player->learnSpell(p.spell);

            RaiseToCap(player, p.skill);
        }

        // The class's own two spells - the only spells it has.
        for (Form const& form : Forms)
            if (!player->HasSpell(form.spell))
                player->learnSpell(form.spell);
    }

    void ChangeClass(Player* player, uint8 newClass)
    {
        ClearTalentsAndGlyphs(player);

        player->SetByteValue(UNIT_FIELD_BYTES_0, 1, newClass);

        DropSkillsTheClassCannotHold(player);
        DropSpellsTheClassCannotHold(player);
        player->LearnDefaultSkills();

        if (newClass == CLASS_TIMEKEEPER)
            TeachTimekeeper(player);
        else
        {
            // What a new character of that class would start with. The rest is at the
            // class trainer, as it would be for anyone.
            player->LearnCustomSpells();
            player->learnQuestRewardedSpells();
        }

        /*
         * The character cache answers name queries - the class other clients colour a name
         * by - and the guild roster for anyone offline. It has no setter for a class, since
         * nothing in the core ever changes one, and reloading the entry from the database
         * would drop the guild and group it carries. So it is corrected in place.
         */
        if (CharacterCacheEntry const* cached = sCharacterCache->GetCharacterCacheByGuid(player->GetGUID()))
            const_cast<CharacterCacheEntry*>(cached)->Class = newClass;

        player->SaveToDB(false, false);
    }

    /*
     * Whether the server can load this character as that class at all. Asked of both races
     * the character has: the real one decides loading, and the current one - which can
     * differ while a race is borrowed - is what the core's own skill and spell helpers
     * look up, without checking for nothing.
     */
    bool HasCreationInfo(Player* player, uint8 playerClass)
    {
        return sObjectMgr->GetPlayerInfo(player->getRace(true), playerClass)
            && sObjectMgr->GetPlayerInfo(player->getRace(), playerClass);
    }

    /// Why this character cannot change class right now, or empty if it can.
    std::string Refusal(Player* player)
    {
        if (uint32(player->GetSession()->GetSecurity()) < RequiredSecurity())
            return "is not on a game master's account. The " + ClassName(CLASS_TIMEKEEPER)
                + " is for game masters' own characters.";

        if (player->IsInCombat())
            return "is in combat.";

        if (player->InBattleground() || player->InArena())
            return "is in a battleground.";

        return {};
    }

    void Finish(ChatHandler* handler, Player* player, uint8 oldClass, uint8 newClass)
    {
        LOG_INFO("module.sanctuarygm", "{} changed {} ({}) from {} to {}.",
            handler->GetSession() ? handler->GetSession()->GetPlayerName() : "The console",
            player->GetName(), player->GetGUID().ToString(), ClassName(oldClass), ClassName(newClass));

        handler->PSendSysMessage("{} is now a |cffffffff{}|r, and has been logged out so their client picks it up.",
            player->GetName(), ClassName(newClass));

        ChatHandler(player->GetSession()).PSendSysMessage(
            "|cffd8b46aSanctuary:|r you are now a {}. Log back in to take it up.", ClassName(newClass));

        player->GetSession()->KickPlayer("SanctuaryGM: class changed");
    }
}

class sanctuary_gm_class_commandscript : public CommandScript
{
public:
    sanctuary_gm_class_commandscript() : CommandScript("sanctuary_gm_class_commandscript") { }

    ChatCommandTable GetCommands() const override
    {
        static ChatCommandTable gmclassCommandTable =
        {
            { "set",    HandleSetCommand,    rbac::RBAC_PERM_COMMAND_CHARACTER_CHANGERACE, Console::Yes },
            { "revert", HandleRevertCommand, rbac::RBAC_PERM_COMMAND_CHARACTER_CHANGERACE, Console::Yes },
        };

        static ChatCommandTable commandTable =
        {
            { "gmclass", gmclassCommandTable },
        };

        return commandTable;
    }

    // The name is required, never taken from the selection: this unmakes a character's
    // class, and a game master standing next to their own main should not be one misplaced
    // click from doing it to them.
    static bool HandleSetCommand(ChatHandler* handler, PlayerIdentifier target)
    {
        Player* player = target.GetConnectedPlayer();

        if (!player)
        {
            handler->SendErrorMessage("{} has to be logged in.", target.GetName());
            return false;
        }

        // Already one: teach anything missing, which is what someone asking again wants.
        // No logout needed - nothing about the class changes.
        if (player->getClass() == CLASS_TIMEKEEPER)
        {
            TeachTimekeeper(player);
            player->SaveToDB(false, false);
            handler->PSendSysMessage("{} is already a {} - taught anything missing: every language, "
                "profession, weapon and armour.", player->GetName(), ClassName(CLASS_TIMEKEEPER));
            return true;
        }

        if (!HasCreationInfo(player, CLASS_TIMEKEEPER))
        {
            handler->SendErrorMessage("The server has no {} for that race - the class SQL has not been applied.",
                ClassName(CLASS_TIMEKEEPER));
            return false;
        }

        if (std::string const why = Refusal(player); !why.empty())
        {
            handler->SendErrorMessage("{} {}", player->GetName(), why);
            return false;
        }

        uint8 const oldClass = player->getClass();
        ChangeClass(player, CLASS_TIMEKEEPER);
        Finish(handler, player, oldClass, CLASS_TIMEKEEPER);
        return true;
    }

    static bool HandleRevertCommand(ChatHandler* handler, PlayerIdentifier target, Tail className)
    {
        Player* player = target.GetConnectedPlayer();

        if (!player)
        {
            handler->SendErrorMessage("{} has to be logged in.", target.GetName());
            return false;
        }

        if (player->getClass() != CLASS_TIMEKEEPER)
        {
            handler->SendErrorMessage("{} is not a {}.", player->GetName(), ClassName(CLASS_TIMEKEEPER));
            return false;
        }

        uint8 const newClass = ParseClass(className);

        if (!newClass || newClass == CLASS_TIMEKEEPER)
        {
            handler->SendErrorMessage("Which class? For example: .gmclass revert {} paladin", player->GetName());
            return false;
        }

        if (!HasCreationInfo(player, newClass))
        {
            handler->SendErrorMessage("{} cannot be a {} - not with that race.", player->GetName(), ClassName(newClass));
            return false;
        }

        if (std::string const why = Refusal(player); !why.empty())
        {
            handler->SendErrorMessage("{} {}", player->GetName(), why);
            return false;
        }

        ChangeClass(player, newClass);
        Finish(handler, player, CLASS_TIMEKEEPER, newClass);
        return true;
    }
};

/*
 * Nobody creates a Timekeeper, game masters included - they are made from a character that
 * already exists. Whatever the client's creation screen offers is only the client's
 * opinion, and a request for class 10 would otherwise succeed: the server has creation info
 * for it, because a Timekeeper could not log in without it.
 */
class sanctuary_gm_class_accountscript : public AccountScript
{
public:
    sanctuary_gm_class_accountscript() : AccountScript("sanctuary_gm_class_accountscript",
        { ACCOUNTHOOK_CAN_ACCOUNT_CREATE_CHARACTER }) { }

    bool CanAccountCreateCharacter(uint32 accountId, uint8 /*race*/, uint8 playerClass) override
    {
        if (playerClass != CLASS_TIMEKEEPER)
            return true;

        LOG_WARN("module.sanctuarygm", "Account {} asked to create a {} and was refused.",
            accountId, ClassName(CLASS_TIMEKEEPER));
        return false;
    }
};

/*
 * The forms, applied and taken off with their auras.
 *
 * A UnitScript rather than an AuraScript on each spell: an AuraScript has to be named in
 * spell_script_names, which means a second place to keep in step for two spells. These
 * hooks see every aura on every unit, so the first thing each does is ask whether this is
 * one of ours, and the answer is no in all but a handful of cases.
 *
 * Taking one form puts the other away first, so the two cannot be half-on together - and
 * the order matters: the other aura is removed BEFORE this one is applied, or its own
 * removal would demorph the form just set.
 */
class sanctuary_gm_class_forms : public UnitScript
{
public:
    // UnitScript takes an "add to scripts" flag before its hook list, unlike the others.
    sanctuary_gm_class_forms() : UnitScript("sanctuary_gm_class_forms", true,
        { UNITHOOK_ON_AURA_APPLY, UNITHOOK_ON_AURA_REMOVE }) { }

    void OnAuraApply(Unit* unit, Aura* aura) override
    {
        Player* player = unit ? unit->ToPlayer() : nullptr;
        Form const* form = (player && aura) ? FindForm(aura->GetId()) : nullptr;

        if (!form)
            return;

        for (Form const& other : Forms)
            if (other.spell != form->spell)
                player->RemoveAurasDueToSpell(other.spell);

        // Smoke first, then the swap behind it.
        player->SendPlaySpellVisual(form->visual);

        player->SetDisplayId(form->display);
        player->SetObjectScale(form->scale);

        // Flight itself is still .gm fly - this turns it on so the form is one gesture
        // rather than two. It goes off with the form, which means stepping out of this one
        // in mid-air is a fall; that is what .gm fly off does too.
        if (form->flies)
            player->SetCanFly(true);
    }

    void OnAuraRemove(Unit* unit, AuraApplication* application, AuraRemoveMode /*mode*/) override
    {
        Player* player = unit ? unit->ToPlayer() : nullptr;
        Form const* form = (player && application && application->GetBase())
            ? FindForm(application->GetBase()->GetId()) : nullptr;

        if (!form)
            return;

        player->SendPlaySpellVisual(form->visual);

        player->DeMorph();
        player->SetObjectScale(1.0f);

        if (form->flies)
            player->SetCanFly(false);
    }
};

/*
 * Casting a form you are already in takes it off, the way a druid's does.
 *
 * A shapeshift behaves that way because the core has a rule for it, and that rule is written
 * for SPELL_AURA_MOD_SHAPESHIFT alone - these carry a dummy and two speed auras instead, so
 * a second cast would simply refresh them and leave a game master stuck in a dragon until
 * they found the buff to right-click.
 *
 * Answered at CheckCast, which is the same moment the core answers it for shapeshifts: the
 * aura is taken off and the cast itself fails with DONT_REPORT, the result that means "this
 * did what it should; say nothing". The removal plays the smoke on its way out, so dropping
 * a form looks the same whichever way it is done.
 */
class sanctuary_gm_class_form_recast : public AllSpellScript
{
public:
    sanctuary_gm_class_form_recast() : AllSpellScript("sanctuary_gm_class_form_recast",
        { ALLSPELLHOOK_ON_SPELL_CHECK_CAST }) { }

    void OnSpellCheckCast(Spell* spell, bool /*strict*/, SpellCastResult& result) override
    {
        if (!spell || !spell->GetSpellInfo())
            return;

        Form const* form = FindForm(spell->GetSpellInfo()->Id);

        if (!form)
            return;

        Unit* caster = spell->GetCaster();

        if (!caster || !caster->HasAura(form->spell))
            return;

        caster->RemoveAurasDueToSpell(form->spell);
        result = SPELL_FAILED_DONT_REPORT;
    }
};

/*
 * Every Timekeeper is topped up at login. The kit only ever grows - a profession or a
 * language added to TeachTimekeeper reaches every Timekeeper already made, with nobody
 * running anything - and it repairs a character that was made before the kit was complete.
 */
class sanctuary_gm_class_playerscript : public PlayerScript
{
public:
    sanctuary_gm_class_playerscript() : PlayerScript("sanctuary_gm_class_playerscript",
        { PLAYERHOOK_ON_LOGIN }) { }

    void OnPlayerLogin(Player* player) override
    {
        if (player->getClass() == CLASS_TIMEKEEPER)
            TeachTimekeeper(player);
    }
};

void AddSC_sanctuary_gm_class()
{
    new sanctuary_gm_class_commandscript();
    new sanctuary_gm_class_accountscript();
    new sanctuary_gm_class_playerscript();
    new sanctuary_gm_class_forms();
    new sanctuary_gm_class_form_recast();
}
